require './main/main.coffee'
require './saga-button/saga-button.coffee'
require './pyridostigmine-button/pyridostigmine-button.coffee'
require './index/index.coffee'
require './npc/npc.coffee'

require './npc/aiyellowb00ks/aiyellowb00ks.coffee'
require './npc/playingcardtachi/playingcardtachi.coffee'
require './npc/catastrophy/catastrophy.coffee'
require './npc/pokerface/pokerface.coffee'
require './npc/pushyf00tmap/pushyf00tmap.coffee'
require './npc/sudoku/sudoku.coffee'
require './levelzero/levelzero.coffee'
